# Clean Image Generator
Generates the needed files for clean, high-quality images.

In [35]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

import pandas as pd
import json

from scripts.data_loader import generate_target_dataset

In [36]:
# full dataset
full_dataset = generate_target_dataset(
    "../data/caption-dataset/annotations/train.json",
    "../data/image-quality-assessment/annotations/train.json",
)
print(f"Full dataset length: {len(full_dataset)}")
print(json.dumps(full_dataset[0], indent=4))

Full dataset length: 23431
{
    "image_id": 0,
    "file_name": "VizWiz_train_00000000.jpg",
    "vizwiz_url": "https://vizwiz.cs.colorado.edu/VizWiz_visualization_img/VizWiz_train_00000000.jpg",
    "text_detected": true,
    "unrecognizable": 1,
    "framing": 3,
    "blur": 1,
    "obstruction": 0,
    "rotation": 0,
    "too dark": 0,
    "too bright": 0,
    "other": 1,
    "no issue": 1,
    "human_captions": [
        {
            "caption": "ITS IS A BASIL LEAVES CONTAINER ITS CONTAINS THE NET WEIGHT TOO.",
            "is_precanned": false,
            "is_rejected": false
        },
        {
            "caption": "A green and white plastic condiment bottle containing Basil leaves.",
            "is_precanned": false,
            "is_rejected": false
        },
        {
            "caption": "Quality issues are too severe to recognize visual content.",
            "is_precanned": true,
            "is_rejected": true
        },
        {
            "caption": "A bottle of spices in a plastic container laying on a surface.",
            "is_precanned": false,
            "is_rejected": false
        },
        {
            "caption": "some basil leaves in a container on a counter",
            "is_precanned": false,
            "is_rejected": false
        }
    ]
}

In [37]:
# load filter dataset
all_filter_data = pd.concat(
    [
        pd.read_csv("./input-data/high-quality_images-rating-4.csv"),
        pd.read_csv("./input-data/high-quality_images-rating-5.csv"),
    ]
)
all_filter_data = all_filter_data[all_filter_data["product"] != "Y"]
display(all_filter_data.head())

# get relevant ids
relevant_ids = all_filter_data["image_id"].unique()
print(f"Number of relevant ids: {len(relevant_ids)}")
print(relevant_ids[0:10])

,image_id,file_name,vizwiz_url,image_preview,product,caption,product.1,brand,variety,code,...,blur,too dark,too bright,obstruction,other,no issue,rotation,image_id.1,Unnamed: 22,text_detected
0,6,VizWiz_train_00000006.jpg,https://vizwiz.cs.colorado.edu/VizWiz_visualiz...,NaN,X,['a jug of equate antiseptic mouthwash citrus ...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,4,0,NaN,NaN,NaN
2,13,VizWiz_train_00000013.jpg,https://vizwiz.cs.colorado.edu/VizWiz_visualiz...,NaN,X,"['I see a can of Dr pepper on the bed', 'White...",NaN,NaN,NaN,NaN,...,0,0,1,0,0,4,1,NaN,NaN,NaN
4,39,VizWiz_train_00000039.jpg,https://vizwiz.cs.colorado.edu/VizWiz_visualiz...,NaN,X,['Italian cuisine style dressing and seasoning...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,4,1,NaN,NaN,NaN
5,50,VizWiz_train_00000050.jpg,https://vizwiz.cs.colorado.edu/VizWiz_visualiz...,NaN,X,['A plastic container of a dairy product with ...,NaN,NaN,NaN,NaN,...,1,0,0,0,0,4,0,NaN,NaN,NaN
8,67,VizWiz_train_00000067.jpg,https://vizwiz.cs.colorado.edu/VizWiz_visualiz...,NaN,X,['There appears to be a light natural colored ...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,4,0,NaN,NaN,NaN

Number of relevant ids: 1494
[  6  13  39  50  67  73  77  97 111 114]

In [38]:
# filter full dataset using relevant ids
filtered_dataset = list(
    filter(lambda x: x["image_id"] in set(relevant_ids), full_dataset)
)
print(f"Filtered dataset length: {len(filtered_dataset)}")

# save filtered dataset
os.makedirs(
    os.path.dirname("../data/study-2-input/high-quality-images/"), exist_ok=True
)
with open(
    "../data/study-2-input/high-quality-images/high-quality-images-filtered.json",
    "w",
    encoding="utf-8",
) as f:
    json.dump(filtered_dataset, f, indent=4)

Filtered dataset length: 1494

In [ ]:
# show summary statistics for each image quality column
filtered_dataset_df = pd.DataFrame.from_dict(filtered_dataset)

# combine all this into a single table
# Create a summary table with value counts for each image quality column
quality_columns = [
    "unrecognizable",
    "blur",
    "framing",
    "obstruction",
    "rotation",
    "too dark",
    "too bright",
    "other",
    "no issue",
]

summary_table = (
    pd.DataFrame(
        {
            col: filtered_dataset_df[col].value_counts().sort_index()
            for col in quality_columns
        }
    )
    .fillna(0)
    .astype(int)
)

display(summary_table)

,unrecognizable,blur,framing,obstruction,rotation,too dark,too bright,other,no issue
0,1416,1188,1013,1469,1390,1421,1404,1472,0
1,64,306,481,25,104,73,90,22,0
2,13,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,896
5,0,0,0,0,0,0,0,0,598